### ISSUE TITLE
eks-d support

### ISSUE THREAD

**Issue by jacobbmay** [defenseunicorns/uds-bundle-software-factory-nutanix#162]
Add bundle support and IaC for eks-d. This issue will link to subtasks needed to accomplish this once I figure out how to create subtasks on it.

```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/delivery-nutanix-image-builder/issues/5
- [ ] https://github.com/defenseunicorns/delivery-nutanix-iac/issues/22
- [ ] https://github.com/defenseunicorns/delivery-nutanix-iac/issues/23
- [ ] https://github.com/defenseunicorns/delivery-nutanix-image-builder/issues/6
- [ ] https://github.com/defenseunicorns/delivery-nutanix-image-builder/issues/7
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/168
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/182
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/183
- [ ] https://github.com/defenseunicorns/delivery-nutanix-iac/issues/24
```

**Comment by JoeHCQ1** [comment]
Could we make this a label? As a task, it is never ending.

**Comment by jacobbmay** [comment]
EKS-D work is OBE and no longer going to be supported
