### ISSUE TITLE
Support configuring multiple image registries in Nexus

### ISSUE THREAD

**Issue by jacobbmay** [defenseunicorns/uds-bundle-software-factory-nutanix#186]
Initially I was only thinking about Nexus requiring a port per image registry. But since we are supporting Nexus pro, we should be able to set this up via subdomain routing that Nexus supports for the pro version.
```[tasklist]
### Tasks
- [x] Get multiple sub-domain registries working in bundle
- [ ] Push updated UDS configs to 1password
- [x] Update docs and reference UDS Config
- [ ] Get PR merged
```

**Comment by JoeHCQ1** [comment]
Customer value: segmented access control is eased with the multiple registries.

Note from Slack:

> Nexus supports creating multiple image registries the same way you might have multiple rpm repos or multiple pypi repos. The difference is registries require either separate ports per registry or subdomain routing so Nexus serves each to a different subdomain (registry1.your.nexus.domain, registry2.your.nexus.domain). Non image repositories in Nexus are served via path routing using the default nexus host and port so we don't need to do anything special to support that.
>
> For supporting multiple registries in Nexus we either need to configure our bundle so that they can pass in a list of subdomains to nexus in a variable for image registries so that istio routing can be configured to route traffic for them to Nexus, or we need to support providing multiple ports so that networking can be setup for each port. The preferred solution is probably the subdomain routing which I think is what mission hero currently uses with their Artifactory.
>
> If you look at what is currently being passed to the nexus package in our bundle, we are only configuring port 5000 for a single image registry. Ideally we get rid of the custom ports and have a variable that allows setting multiple registry domains that all route to nexus on port 443.
>
> Then Nexus can use its built in subdomain routing and we don't need to worry about them knowing to configure a port per registry in addition to subdomains for istio routing.

**Comment by JoeHCQ1** [comment]
- The package repo: https://github.com/defenseunicorns/uds-package-nexus
- The upstream BigBang chart supports multiple registries specified by host and port: https://repo1.dso.mil/big-bang/product/packages/nexus/-/blob/main/chart/values.yaml?ref_type=heads#L240
- The BigBang chart has an upstream, can look into it if necessary, the values file has a comment about the end of big bang additions
- To create the multiple virtual services, I'm curious to see if UDS packages already support multiple services, and if so, how we can pass those in via the UDS config because _this must be install time configurable, not part of the bundle creation_.

**Comment by JoeHCQ1** [comment]
This work is about done afaik so I've moved this up a milestone and changed the predicted end-date.

**Comment by JoeHCQ1** [comment]
Updates since last comment:

- Got a metrics-server error on deploy which turned out to be caused by the following. At the initial deploy, the admin password to nexus was in a secret which the metrics server job used to add a prometheus role. Nexus then stores that password in postgres. If you delete the namespace and the package though, you'll get a new generated password in the secret, and the metrics job will get a 401 on connection. Pair programmed for most of Friday afternoon and we didn't think of this until Monday.

- Neither @jacobbmay nor I are able to access the registry setting the dev env as an `insecure-registry` in the docker daemon.json. Docker tries to access the repo at `http` instead of just trusting the `https`. So, it's necessary to add the `ca-bundle.pem` from 1-pass to your truststore (past it to a file as an intermediary step). This https://www.bounca.org/tutorials/install_root_certificate.html had better instructions than Apple. 

- Docker client authentication will not work without adding the `Docker Bearer Token Realm` and it is not enabled by default. Enabled that today, not sure if I need to bounce anything to get the setting active.

Here are some links of note
- https://help.sonatype.com/en/docker-authentication.html (mentions Docker Bearer Token)
- https://help.sonatype.com/en/docker-subdomain-connector.html all about the subdomain routing which is what we want.
- https://help.sonatype.com/en/ssl-and-repository-connector-configuration.html is easier to find but mostly presumes port-based access.

**Comment by JoeHCQ1** [comment]
The 401 error I get right now on login is logged in the tenant gateway pod:

```bash

```

```log
[2024-10-22T14:47:56.393Z] "GET /v2/ HTTP/1.1" 401 - via_upstream - "-" 0 0 5 4 "192.168.5.68" "docker/27.2.0 go/go1.21.13 git-commit/3ab5c7d kernel/6.10.4-linuxkit os/linux arch/arm64 UpstreamClient(Docker-Client/27.2.0 \(darwin\))" "4e5b5580-56a0-4cd6-927b-17d2ba5f584b" "unpredictable-name.nexus.mtsi-dev.bigbang.dev" "192.168.4.83:8081" outbound|8081||nexus-repository-manager.nexus.svc.cluster.local 192.168.4.203:35530 192.168.4.203:443 192.168.5.68:10901 unpredictable-name.nexus.mtsi-dev.bigbang.dev -
[2024-10-22T14:49:19.113Z] "GET /v2/ HTTP/1.1" 401 - via_upstream - "-" 0 113 4 3 "192.168.5.68" "docker/27.2.0 go/go1.21.13 git-commit/3ab5c7d kernel/6.10.4-linuxkit os/linux arch/arm64 UpstreamClient(Docker-Client/27.2.0 \(darwin\))" "e4c3af45-4cbb-40eb-92db-a4c38aa47cf8" "unpredictable-name.nexus.mtsi-dev.bigbang.dev" "192.168.4.83:8081" outbound|8081||nexus-repository-manager.nexus.svc.cluster.local 192.168.4.203:52182 192.168.4.203:443 192.168.5.68:15390 unpredictable-name.nexus.mtsi-dev.bigbang.dev -
[2024-10-22T14:49:19.471Z] "GET /v2/ HTTP/1.1" 401 - via_upstream - "-" 0 0 5 5 "192.168.5.68" "docker/27.2.0 go/go1.21.13 git-commit/3ab5c7d kernel/6.10.4-linuxkit os/linux arch/arm64 UpstreamClient(Docker-Client/27.2.0 \(darwin\))" "3273c1c7-3d2d-43be-b90b-bf1ee2851fec" "unpredictable-name.nexus.mtsi-dev.bigbang.dev" "192.168.4.83:8081" outbound|8081||nexus-repository-manager.nexus.svc.cluster.local 192.168.4.203:35530 192.168.4.203:443 192.168.5.68:11290 unpredictable-name.nexus.mtsi-dev.bigbang.dev -
```

Note there was a `301` logged too probably from when I was hitting it with an `http` request due to the `insecure-registries` setting in the docker daemon.

**Comment by JoeHCQ1** [comment]
Explicitly adding the subdomain to the tenant gateway didn't fix it. 

Error:
```log
[2024-10-22T14:55:33.801Z] "GET /v2/ HTTP/1.1" 401 - via_upstream - "-" 0 0 5 5 "192.168.5.68" "docker/27.2.0 go/go1.21.13 git-commit/3ab5c7d kernel/6.10.4-linuxkit os/linux arch/arm64 UpstreamClient(Docker-Client/27.2.0 \(darwin\))" "84c3eac7-575b-4c2b-be26-09807c85df4d" "unpredictable-name.nexus.mtsi-dev.bigbang.dev" "192.168.4.83:8081" outbound|8081||nexus-repository-manager.nexus.svc.cluster.local 192.168.4.203:52182 192.168.4.203:443 192.168.5.68:15748 unpredictable-name.nexus.mtsi-dev.bigbang.dev -
```

Tenant Gateway snippet
```yaml
  - hosts:
    - '*.mtsi-dev.bigbang.dev'
    - '*.nexus.mtsi-dev.bigbang.dev'
    - unpredictable-name.nexus.mtsi-dev.bigbang.dev
    port:
      name: https-tenant
      number: 443
      protocol: HTTPS
    tls:
      credentialName: gateway-tls
      minProtocolVersion: TLSV1_3
      mode: SIMPLE
```

Removing `unpredictable-name.nexus.mtsi-dev.bigbang.dev` from the hosts list.

**Comment by JoeHCQ1** [comment]
The error code means that Nexus is sending the 401 (`via_upstream`), see [Envoy log format](https://istio.io/latest/docs/tasks/observability/logs/access-log/) for clarity on how to parse those logs. The table speaks vertically T->D of what the log portrays L->R. I suspect I'm not allowed to log in with a mere username & password.

**Comment by JoeHCQ1** [comment]
**Another configuration step required going forward:** you must also enable user tokens under the Security settings and then generate them for your user. Only with the token username and token password can you login.

 
<img width="1037" alt="Screenshot 2024-10-22 at 11 11 24 AM" src="https://github.com/user-attachments/assets/79bf844a-181d-4277-9d7f-93fa5c1a7744">

**Comment by JoeHCQ1** [comment]
Push/pull works now:

<img width="1115" alt="Screenshot 2024-10-22 at 11 12 45 AM" src="https://github.com/user-attachments/assets/0ac5c246-2e4f-48e6-8813-16041f0982f9">

And I can create a new repository:

![Screenshot 2024-10-22 at 11 14 23 AM](https://github.com/user-attachments/assets/e2df281c-d3be-4088-9dfe-6397ce1533f6)
![Screenshot 2024-10-22 at 11 15 04 AM](https://github.com/user-attachments/assets/afbc0d04-5ca9-40ce-b369-07165495c4f5)

And then (sign-in) and push/pull from it w/o changes to the infrastructure:

<img width="1212" alt="Screenshot 2024-10-22 at 11 17 09 AM" src="https://github.com/user-attachments/assets/70ac408f-c90a-4ca2-b073-a1871948372c">

Used the same token as for the `unexpected-name` registry b/c it's user-scoped not repository-scoped.
