### ISSUE TITLE
Get every app integrated with Keycloak

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#46]
Working with Marketplace, udate all bundle app packages to include OIDC/keycloak integration via UDS standard patterns:

```[tasklist]
### Tasks
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/47
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/48
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/49
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/50
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/51
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/52
- [x] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/53
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/205
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/204
- [ ] https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/issues/206
```

**Comment by s-ollek** [comment]
@blancharda should we tag this as `MVP` as well? See it's a monolith issue, just curious. I do see that #53 #47 are tagged, so that's probably well enough.

**Comment by blancharda** [comment]
We certainly COULD, but I think it's okay as is. 
The intent of this issue was to track <all the SSO things> from a single viewpoint.

The two that are relevant to the MVP are the ones with the tag 👍

**Comment by JoeHCQ1** [comment]
Cleared it from this milestone because we're so far past 0.3.0. Also, we need to define what "done" means. Right now, you _can_ integrate Jira and Confluence with Keycloak via click-ops. It may be impossible with these being Atlassian tools to entirely avoid click-ops, so this is arguably done.

That said, we should have some documentation to tell people what to do here, even if only linking to other docs. And it's not likely "done" until then.

**Comment by JoeHCQ1** [comment]
This is sort of done. Every app _can_ integrate with Jira minus those currently with CA cert problems (bug being tracked #204 #205 #206). What remains is mostly to _document_ this process and remove the click-ops if possible. IIRC, Jira is supposed to connect to Keycloak, and then the other Atlassian tools to Jira. This can be done, but could be tricky.

**Comment by JoeHCQ1** [comment]
This is done minus the lack of CA certs. That we should document that integration is manual doesn't make this not done.

**Comment by jacobbmay** [comment]
Gonna mark this as done. Everything that can be integrated automatically is. Atlassian suite has clickops steps required that prevent complete automation at this point in time.

If completely automated integration is ever supported, that should be resolved in the uds-package repos.
