### ISSUE TITLE
Update default resource allocation for each package

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-bundle-software-factory-nutanix#58]
Update default resource allocation based on upstream recommendations and any known information about target user counts.

```[tasklist]
### Tasks
- [ ] Update resources for Gitlab
- [ ] Update resources for Jira
- [ ] Update resources for Confluence
- [ ] Update resources for Nexus
- [ ] Update resources for Mattermost
- [ ] Update resources for Sonarqube
- [ ] Update resources for GL Runners
- [ ] Update resources for Loki
- [ ] Update resources for Prom Stack
- [ ] Update resources for Velero
- [ ] Update resources for uds and pepr
- [ ] Update resources for Keycloak
```

**Comment by blancharda** [comment]
These should be relatively quick, so I won't make new issues for each -- please leave a comment with the associated PR when one is checked off.

(we can revisit this^ if needed)

**Comment by anthonywendt** [comment]
Merged in a lot of resource config across the bundle. I'm sure there will be more resource config to tweak and expose as we march on.
https://github.com/defenseunicorns/uds-bundle-software-factory-nutanix/pull/139
